import KratosMultiphysics
import KratosMultiphysics.StructuralApplication
import KratosMultiphysics.BRepApplication
import KratosMultiphysics.FiniteCellApplication
import KratosMultiphysics.FiniteCellStructuralApplication
print("Kratos is loaded successfully")

